config/routes.rb
Rails.application.routes.draw do
  resources :municipes, except: %i[show destroy]

  root to: 'municipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :municipe, inverse_of: :endereco

  validates :cep,         presence: true, length: { maximum: 200 }
  validates :logradouro,  presence: true, length: { maximum: 200 }
  validates :bairro,      presence: true, length: { maximum: 200 }
  validates :cidade,      presence: true, length: { maximum: 200 }
  validates :uf,          presence: true, length: { maximum: 200 }

  validates :complemento, length: { maximum: 200 }
  validates :ibge_code,   length: { maximum: 200 }

  def full_address
    "#{logradouro}, #{complemento}, #{bairro}, CEP: #{cep}"
  end
end

app/models/municipe.rb
class Municipe < ApplicationRecord
  include MunicipeSearcheable

  enum status: { ativo: 'ativo', inativo: 'inativo' }, _default: 'ativo'

  has_one_attached :avatar do |attachable|
    attachable.variant :thumb_40, resize_to_limit: [40, 40]
    attachable.variant :thumb_80, resize_to_limit: [80, 80]
  end

  has_one :endereco, inverse_of: :municipe, required: true
  accepts_nested_attributes_for :endereco

  validates :status, inclusion: { in: statuses.keys }

  validates :name,        presence: true, length: { maximum: 200 }
  validates :cpf,         presence: true, cpf: true, uniqueness: { case_sensitive: true }
  validates :phone,       presence: true, length: { maximum: 200 }

  validates :cns,         '::CnsBrazil::Cns': true

  validates :email, presence: true, confirmation: true, length: { maximum: 200 }
  validates :email, email_format: { message: 'email inválido' }
  validates :email_confirmation, presence: true, length: { maximum: 200 }

  validates :birth_date, comparison: { less_than_or_equal_to: Date.today }

  paginates_per 10
end

app/models/municipe_searcheable.rb
module MunicipeSearcheable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks

    mapping do
      indexes :name, type: :text
      indexes :cpf, type: :text
      indexes :cns, type: :text
      indexes :email, type: :text
    end

    def self.search(query)
      __elasticsearch__.search(query)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/municipes_controller.rb
class MunicipesController < ApplicationController
  before_action :set_municipe, only: %i[edit update]

  def index
    Municipe.__elasticsearch__.create_index!

    @municipes = if filter_params.blank?
                   Municipe.includes(:endereco).page(params[:page])
                 else
                   Municipe.includes(:endereco).search(filter_params).page(params[:page]).records
                 end
  end

  def new
    @municipe = Municipe.new
    @municipe.build_endereco
  end

  def edit; end

  def create
    creator = CreateMunicipe.new(params: municipe_params)

    respond_to do |format|
      if creator.submit
        format.html { redirect_to municipes_url, notice: 'Munícipe criado com sucesso' }
      else
        @municipe = creator.municipe
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    updater = UpdateMunicipe.new(params: municipe_params, municipe: @municipe)

    respond_to do |format|
      if updater.submit
        format.html { redirect_to municipe_url(@municipe), notice: 'Munícipe atualizado com sucesso.' }
      else
        @municipe = updater.municipe
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_municipe
    @municipe = Municipe.find(params[:id])
  end

  def filter_params
    params['query'] || ''
  end

  def municipe_params
    params.require(:municipe)
          .permit(
            :name,
            :cpf,
            :cns,
            :email,
            :email_confirmation,
            :birth_date,
            :phone,
            :status,
            :avatar,
            endereco_attributes: %i[
              id cep logradouro complemento bairro cidade uf ibge_code
            ]
          )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_alert.html.erb
<% flash.each do |name, msg| %>
  <%- alert = name == 'alert' %>
  <%- attr_class = alert ? 'warning' : 'success' %>
  <div class="alert alert-<%= attr_class %> rounded-0" role="alert">
    <%- if alert  %>
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 mr-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
      </svg>
    <% else %>
      <i class="far fa-check-circle"></i>
    <% end %>
    <span class="ms-3"><%= msg %></span>
  </div>
<% end %>

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="<%= municipes_path %>">Municipes</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarScroll">
      <ul class="navbar-nav my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active <%= current_page?(municipes_path) ? 'fw-bold' : '' %>" aria-current="page" href="<%= municipes_path %>">Listar</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active <%= current_page?(new_municipe_path) ? 'fw-bold' : '' %>" aria-current="page" href="<%= new_municipe_path %>">Novo</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <header class="sticky-top">
      <section>
        <%= render 'layouts/nav_bar' %>
      </section>
    </header>

    <main class="container">
      <div class="m-3">
        <%= render 'layouts/flash_alert' %>
      </div>
      <div class="m-3">
      <%= yield %>
    </main>
  </body>
</html>

app/views/municipes/_form.html.erb
<%= simple_form_for(@municipe, data: { controller: 'masks' }) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class="row">
      <div class="col-md-3 d-flex flex-column align-items-center">

        <% if @municipe.avatar.representable? %>
          <picture>
            <%= image_tag @municipe.avatar.variant(:thumb_80), class: 'img-fluid img-thumbnail' %>
          </picture>
        <% else %>
          <picture>
            <%= image_tag 'avatar.png', width: '80' %>
          </picture>
        <% end %>

        <%= f.file_field :avatar, class: 'form-control form-control-sm', id: 'formFileSm' %>
        <hr />

        <div class="d-flex flex-column align-items-start">
          <%= f.collection_radio_buttons :status, Municipe.statuses.to_a, :first, :last %>
        </div>
      </div>
      <div class="col-md-9">
        <%= f.input :name %>
        <div class="row">
          <div class="col-md-6">
            <%= f.input :cpf, input_html: { 'data-masks-target': 'cpf' } %>
          </div>
          <div class="col-md-6">
            <%= f.input :cns, input_html: { 'data-masks-target': 'cns' } %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <%= f.input :email %>
          </div>
          <div class="col-md-6">
            <%= f.input :email_confirmation %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <%= f.input :birth_date, html5: true, input_html: { max: Date.today } %>
          </div>
          <div class="col-md-6">
            <%= f.input :phone, input_html: { 'data-masks-target': 'cellPhone' } %>
          </div>
        </div>

        <hr />
        <h5>Endereço</h5>
        <%= f.simple_fields_for :endereco do |endereco_form| %>

        <div class="row">
          <div class="col-md-3">
            <%= endereco_form.input :cep, input_html: { 'data-masks-target': 'cep' } %>
          </div>
          <div class="col-md-9">
            <%= endereco_form.input :logradouro %>
          </div>
        </div>
          <%= endereco_form.input :complemento %>
          <%= endereco_form.input :bairro %>

        <div class="row">
          <div class="col-md-6">
            <%= endereco_form.input :cidade %>
          </div>
          <div class="col-md-3">
            <%= endereco_form.input :uf %>
          </div>
          <div class="col-md-3">
            <%= endereco_form.input :ibge_code %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="form-actions d-flex justify-content-between mt-3">
    <%= link_to '<i class="bi bi-arrow-left"></i>'.html_safe, municipes_path, title: 'voltar', class: 'btn btn-outline-primary rounded-pill' %>
    <%= f.button :submit, class: 'btn btn-outline-primary rounded-pill' %>
  </div>
<% end %>

app/views/municipes/edit.html.erb
<div class="card shadow-sm">
  <div class="card-header bg-transparent border-0">
    Editar Munícipe
  </div>
  <div class="card-body">
    <%= render "form", municipe: @municipe %>
  </div>
</div>

app/views/municipes/index.html.erb
<% unless @municipes.empty? %>
  <form class="d-flex w-100 mb-3" role="search">
    <input
      class="form-control me-2"
      type="search"
      placeholder="Pesuise por nome, email, cpf ou cns"
      aria-label="Search"
      value="<%= params.dig(:query) %>"
      name="query">
    <button class="btn btn-outline-primary rounded-pill" type="submit">Pesquisar</button>
    <%= link_to "Limpar", municipes_path, title: 'Editar', class: 'btn btn-outline-primary rounded-pill' %>
  </form>
<% end %>

<div class="card shadow-sm">
  <div class="card-header bg-transparent border-0">
    Munícipes
  </div>
  <div class="card-body">
    <% if @municipes.empty? %>
      <div class="d-grid">
        <%= link_to "Nenhum munícipe cadastrado, Clique para cadastrar o primeiro", new_municipe_path, title: 'Novo Munícipe', class: 'btn btn-outline-primary btn-sm rounded-pill' %>
      </div>
    <% else %>
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">Nome</th>
              <th scope="col">Documentos</th>
              <th scope="col">Email</th>
              <th scope="col">Status</th>
              <th scope="col"></th>
            </tr>
          </thead>

          <tbody>
            <% @municipes.each do |municipe| %>
              <tr>
                <td>
                  <% if municipe.avatar.representable? %>
                    <picture>
                      <%= image_tag municipe.avatar.variant(:thumb_40), class: 'img-fluid img-thumbnail' %>
                    </picture>
                  <% else %>
                    <picture>
                      <%= image_tag 'avatar.png', width: '40' %>
                    </picture>
                  <% end %>
                </td>
                <td><%= municipe.name %></td>
                <td>
                  <p class="m-0"><span class="badge bg-secondary">CPF:</span> <%= municipe.cpf %></p>
                  <p class="m-0"><span class="badge bg-secondary">CNS:</span> <%= municipe.cns %></p>
                </td>
                <td><%= municipe.email %></td>
                <td>
                  <span class="badge <%= municipe.ativo? ? 'text-bg-success' : 'text-bg-danger' %>">
                    <%= municipe.status.upcase %>
                  </span>
                </td>
                <td>
                  <%= link_to "Editar", edit_municipe_path(municipe), title: 'Editar', class: 'btn btn-outline-primary btn-sm rounded-pill' %>

                  <button class="btn btn-outline-primary btn-sm rounded-pill" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= municipe.id %>" aria-expanded="false" aria-controls="collapseExample">
                    Detalhes
                  </button>
                </td>
              </tr>

              <tr class="collapse accordion-collapse" id="collapse<%= municipe.id %>" data-bs-parent=".table">
                <td colspan="6">
                  <div class="row">
                    <div class="col-md-4">
                      <h5>Pessoal</h5>
                      <small><strong>Data de Nascimento:</strong> <br /> <%= municipe.email %></small>
                      <br>
                      <small><strong>Telefone:</strong> <br /> <%= municipe.phone %></small>
                    </div>
                    <div class="col-md-8">
                      <h5>Residência</h5>

                      <small><strong>Endereço:</strong> <%= municipe.endereco&.full_address %></small> <br/>
                      <small><strong>Municipio:</strong> <%= municipe.endereco&.cidade %> - <%= municipe.endereco&.uf %></small>
                    </div>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <div class="d-flex justify-content-center">
          <%= paginate @municipes, theme: 'bootstrap-5' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/municipes/new.html.erb
<div class="card shadow-sm">
  <div class="card-header bg-transparent border-0">
    Novo Munícipe
  </div>
  <div class="card-body">
    <%= render "form", municipe: @municipe %>
  </div>
</div>